- name: Installer et configurer MyHostWeb avec Fail2Ban
  hosts: localhost
  become: yes  # Pour devenir sudo

  tasks:
    - name: Mise à jour des packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
    
    - name: Install Zsh
      apt:
        name: zsh
        state: present
        update_cache: yes

    - name: Get the Zsh path
      command: which zsh
      register: zsh_path
      changed_when: false

    - name: Change the default shell to Zsh for the current user
      command: chsh -s {{ zsh_path.stdout }}
      when: zsh_path.stdout != ""
      become_user: "{{ ansible_env.USER }}"

    - name: Verify the shell change
      become: no
      command: echo $SHELL
      register: shell_after
      changed_when: false

    - debug:
        msg: "The shell before change was {{ ansible_env.SHELL }} and after change is {{ shell_after.stdout }}"

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Oh My Zsh
      shell: zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh
        executable: /bin/zsh

    - name: Clone Powerlevel10k theme
      git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        version: master
      register: p10k

    - name: Add Powerlevel10k theme to .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME=.*'
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        state: present

    - name: Install zsh-autosuggestions
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting
      git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Add plugins to .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins=.*'
        line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'
        state: present

    - name: Installer Zip
      ansible.builtin.apt:
        name: zip
        state: present

    - name: Installer Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Démarrer le service Docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: Activer le service Docker
      ansible.builtin.service:
        name: docker
        enabled: yes

    - name: Installer Docker Compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Créer le réseau Docker
      ansible.builtin.docker_network:
        name: myhost_network
        state: present

    - name: Créer le volume Docker
      ansible.builtin.docker_volume:
        name: myhostweb_data
        state: present

    - name: Installer Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

    - name: Copier la configuration de Fail2Ban
      ansible.builtin.copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        mode: '0644'

    - name: Configurer Fail2Ban avec maxretry = 5, bantime = 10h, findtime = 10m
      ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        line: |
          [DEFAULT]
          maxretry = 5
          bantime = 10h
          findtime = 10m
      notify: Restart Fail2Ban

    - name: Démarrer le service Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes

  # Handler pour redémarrer Fail2Ban après la modification de la configuration
  handlers:
    - name: Restart Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
