- name: Installer et configurer MyHostWeb avec Fail2Ban
  hosts: localhost
  become: yes  # Pour devenir sudo

  tasks:
    - name: Installer Zip
      ansible.builtin.apt:
        name: zip
        state: present

    - name: Installer Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Démarrer le service Docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: Activer le service Docker
      ansible.builtin.service:
        name: docker
        enabled: yes

    - name: Installer Docker Compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Créer le réseau Docker
      ansible.builtin.docker_network:
        name: myhost_network
        state: present

    - name: Créer le volume Docker
      ansible.builtin.docker_volume:
        name: myhostweb_data
        state: present

    - name: Installer Fail2Ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

    - name: Copier la configuration de Fail2Ban
      ansible.builtin.copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        mode: '0644'

    - name: Configurer Fail2Ban avec maxretry = 5, bantime = 10h, findtime = 10m
      ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        line: |
          [DEFAULT]
          maxretry = 5
          bantime = 10h
          findtime = 10m
      notify: Restart Fail2Ban

    - name: Démarrer le service Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes

  # Handler pour redémarrer Fail2Ban après la modification de la configuration
  handlers:
    - name: Restart Fail2Ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
