version: '3.8'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    ports:
      - '80:80' # ne pas modifier
      - '81:81'
      - '443:443' # ne pas modifier
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: "${DB_MYSQL_HOST}"
      DB_MYSQL_PORT: "${DB_MYSQL_PORT}"
      DB_MYSQL_USER: "${MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      DB_MYSQL_NAME: "${DB_MYSQL_NAME}"
    volumes:
      - /srv/docker/nginx-proxy-manager/data:/data
      - /srv/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - myhost_network

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /srv/docker/nginx-proxy-manager/mysql:/var/lib/mysql
    networks:
      - myhost_network

networks:
  myhost_network:
    external: true
