version: '3'

services:
  # Service Nginx Proxy Manager
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./myhostweb_data/nginx/data:/data
      - ./myhostweb_data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - myhost_network
    restart: always

volumes:
  myhostweb_data:

networks:
  myhost_network:
    external: true
