version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - myhost_network
    restart: always

volumes:
  portainer_data:

networks:
  myhost_network:
    external: true
